# Generated by Django 5.1.4 on 2024-12-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizzamodel_name_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
    ]
